### ISSUE TITLE
I get error:  PHP Fatal error:  Uncaught Error: Class 'Quince\\PersianGD\\GDTool' not found

### ISSUE THREAD

**Issue by shamsat** [QuincePHP/persian-gd#6]
I installed the persian-gd library with composer this is the folders sequence:
vendor/Quince/PersianGD/GDTool
GDTool folder contains the GDTool.php and others.
I run the simple usage code in the vendor folder as the index.php but get this error:
`
[Wed Jul 26 22:08:02.367946 2017] [:error] [pid 2884] [client 192.168.1.100:34002] PHP Fatal error:  Uncaught Error: Class 'Quince\\PersianGD\\GDTool' not found in /var/www/me.usa.cc/persian/vendor/index.php:3\nStack trace:\n#0 {main}\n  thrown in /var/www/me.usa.cc/persian/vendor/index.php on line 3
`
This is index.php:
`
$gdTool = new Quince\PersianGD\GDTool();
$myText = "ﻢﻧ ﺶﻤﺳ ﻪﺴﺘﻣ";
$gdTool->setFileName('suns.jpg')
               ->addLine($myText)
                      ->build();
`

**Comment by behzadsh** [comment]
Seems like it cannot autoload the class.
Did you include `autoload.php` in your `index.php`?

your `index.php` should be like this:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$gdTool = new Quince\PersianGD\GDTool();
$myText = "ﻢﻧ ﺶﻤﺳ ﻪﺴﺘﻣ";
$gdTool->setFileName('suns.jpg')->addLine($myText)->build();
```

**Comment by shamsat** [comment]
Thanks for reply,  i run the above updated code from the dir that contains the:
`
composer.json  LICENSE  README.md  src vendor
`
Inside the vendor is autoload.php Quince dir. 
but still get this error:
`
PHP Fatal error:  Uncaught Error: Class 'Quince\\PersianGD\\GDTool' not found in /var/www/me.usa.cc/persian/index.php:3\nStack trace:\n#0 {main}\n  thrown in /var/www/me.usa.cc/persian/index.php on line 3
`

**Comment by shamsat** [comment]
Thanks for reply i run the above updated code but now get this error:
`
PHP Warning:  imagettftext(): Could not find/open font in /var/www/me.usa.cc/persian/vendor/quince/persian-gd/src/GDTool.php on line 457
`
I put the fonts in fonts dir  and put the line bellow just uder the require line in the index.php:
`
$font = __DIR__ .'/fonts/BahijRegular.ttf';
`
but stil get the not/find open font error.

**Comment by behzadsh** [comment]
Is your font file name, exactly like what you write in your code? font parameter is case sensitive.

for example check that filename extension is not uppercase.

**Comment by behzadsh** [comment]
I close this issue as it's not package related!
