### ISSUE TITLE
setUseLocalNumber not let continuing the chain

### ISSUE THREAD

**Issue by aliwesome** [QuincePHP/persian-gd#8]
this function `setUseLocalNumber` method does not return `$this` to let the chain continues.

**Comment by aliwesome** [comment]
this causes following error:
`Call to a member function setFileName() on null`

**Comment by behzadsh** [comment]
Hi,
Thank you for reporting this issue.
I will check it.

**Comment by behzadsh** [comment]
@aliwesome I updated the codes, although the `setUseLocalNumber` method did return the `GDTool`. Would you update and check again?
